param(
  [Parameter(Mandatory=$true)][string]$PokemonMovesCsv,
  [Parameter(Mandatory=$true)][string]$MovesCsv,
  [string]$ModRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'

# These are the physical machine rosters on the supported cartridges. PokeAPI
# supplies which canonical species can learn them by machine in at least one
# main-series game; the runtime installer then resolves the cart's exact id.
$gen1 = @(
  'mega-punch','razor-wind','swords-dance','whirlwind','mega-kick','toxic',
  'horn-drill','body-slam','take-down','double-edge','bubble-beam','water-gun',
  'ice-beam','blizzard','hyper-beam','pay-day','submission','counter',
  'seismic-toss','rage','mega-drain','solar-beam','dragon-rage','thunderbolt',
  'thunder','earthquake','fissure','dig','psychic','teleport','mimic',
  'double-team','reflect','bide','metronome','self-destruct','egg-bomb',
  'fire-blast','swift','skull-bash','soft-boiled','dream-eater','sky-attack',
  'rest','thunder-wave','psywave','explosion','rock-slide','tri-attack',
  'substitute','cut','fly','surf','strength','flash'
)
$gen2 = @(
  'dynamic-punch','headbutt','curse','rollout','roar','toxic','zap-cannon',
  'rock-smash','psych-up','hidden-power','sunny-day','sweet-scent','snore',
  'blizzard','hyper-beam','icy-wind','protect','rain-dance','giga-drain',
  'endure','frustration','solar-beam','iron-tail','dragon-breath','thunder',
  'earthquake','return','dig','psychic','shadow-ball','mud-slap','double-team',
  'ice-punch','swagger','sleep-talk','sludge-bomb','sandstorm','fire-blast',
  'swift','defense-curl','thunder-punch','dream-eater','detect','rest','attract',
  'thief','steel-wing','fire-punch','fury-cutter','nightmare','cut','fly','surf',
  'strength','flash','whirlpool','waterfall'
)

$engineNames = @{
  'psychic'='PSYCHIC_M'; 'self-destruct'='SELFDESTRUCT';
  'soft-boiled'='SOFTBOILED'; 'solar-beam'='SOLARBEAM';
  'thunder-punch'='THUNDERPUNCH'; 'dynamic-punch'='DYNAMICPUNCH';
  'dragon-breath'='DRAGONBREATH'
}
function Engine-Name([string]$slug) {
  if ($engineNames.ContainsKey($slug)) { return $engineNames[$slug] }
  return $slug.ToUpperInvariant().Replace('-', '_')
}

$wanted1 = @{}; foreach ($m in $gen1) { $wanted1[$m] = Engine-Name $m }
$wanted2 = @{}; foreach ($m in $gen2) { $wanted2[$m] = Engine-Name $m }
$moveSlugs = @{}; Import-Csv -LiteralPath $MovesCsv | ForEach-Object {
  $moveSlugs[[int]$_.id] = $_.identifier
}

$byDex1 = @{}; $byDex2 = @{}
$reader = [IO.File]::OpenText((Resolve-Path -LiteralPath $PokemonMovesCsv))
try {
  $null = $reader.ReadLine()
  while (($line = $reader.ReadLine()) -ne $null) {
    $c = $line.Split(',')
    if ($c.Count -lt 4 -or [int]$c[3] -ne 4) { continue }
    $dex = [int]$c[0]
    if ($dex -lt 1 -or $dex -gt 1025) { continue }
    $slug = $moveSlugs[[int]$c[2]]
    if ($wanted1.ContainsKey($slug)) {
      if (-not $byDex1.ContainsKey($dex)) { $byDex1[$dex] = @{} }
      $byDex1[$dex][$wanted1[$slug]] = $true
    }
    if ($wanted2.ContainsKey($slug)) {
      if (-not $byDex2.ContainsKey($dex)) { $byDex2[$dex] = @{} }
      $byDex2[$dex][$wanted2[$slug]] = $true
    }
  }
} finally { $reader.Dispose() }

$nationalPath = Join-Path $ModRoot 'data/species/generated/national.lua'
$species = @()
$current = $null
foreach ($line in [IO.File]::ReadLines($nationalPath)) {
  if ($line -match '^    ([A-Z0-9_]+) = \{$') { $current = $Matches[1]; continue }
  if ($current -and $line -match '^      dex = (\d+),$') {
    $species += [pscustomobject]@{ id=$current; dex=[int]$Matches[1] }
    $current = $null
  }
}

function Emit-Table($lookup, [int]$nativeMax) {
  $lines = [Collections.Generic.List[string]]::new()
  foreach ($s in ($species | Sort-Object dex,id)) {
    $moves = $lookup[$s.dex]
    if ($moves -and $s.dex -gt $nativeMax) {
      $quoted = (($moves.Keys | Sort-Object) | ForEach-Object { '"' + $_ + '"' }) -join ', '
      $lines.Add(('    {0} = {{ dex = {1}, moves = {{ {2} }} }},' -f $s.id,$s.dex,$quoted))
    }
  }
  return $lines
}

$out = [Collections.Generic.List[string]]::new()
$out.Add('-- Generated by tools/build_tmhm.ps1 from PokeAPI pokemon_moves.csv.')
$out.Add('-- Only the supported cartridges'' native TM/HM move rosters appear.')
$out.Add('return {')
$out.Add('  gen1 = {'); $out.AddRange([string[]](Emit-Table $byDex1 151)); $out.Add('  },')
$out.Add('  gen2 = {'); $out.AddRange([string[]](Emit-Table $byDex2 251)); $out.Add('  },')
$out.Add('}')
$outputPath = Join-Path $ModRoot 'data/species/generated/tmhm_compatibility.lua'
[IO.File]::WriteAllLines($outputPath, $out, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $outputPath"
